index:
   path: /
   controller: App\Controller\DefaultController::index
seller:
   path: /seller
   controller: App\Controller\SellerController::index
buyers:
   path: /buyer
   controller: App\Controller\BuyerController::index
courier:
   path: /courier
   controller: App\Controller\CourierController::index
order:
   path: /order
   controller: App\Controller\OrderController::index
order_list:
   path: /order/list
   controller: App\Controller\OrderController::list
order_id:
   path: /order/{id}
   controller: App\Controller\OrderController::getOrder   
order_add:
   path: /order/addOrder
   controller: App\Controller\OrderController::addOrder
   condition:  "context.getMethod() in ['POST']"
   methods: POST
order_new:
   path: /new/order/
   controller: App\Controller\OrderController::new
order_delivery_price:
   path: /order/{id}/delivery/price
   controller: App\Controller\OrderController::deliveryPrice   
product:
   path: /product
   controller: App\Controller\ProductController::index
product_id:
   path: /product/{id}
   controller: App\Controller\ProductController::showProduct   
product_edit:
   path: /product/{id}/edit
   controller: App\Controller\ProductController::updateProduct
product_create:
   path: /create/product
   controller: App\Controller\ProductController::createProduct
product_delete:
   path: /product/{id}/delete
   controller: App\Controller\ProductController::deleteProduct   